/*
 * Copyright 2026, Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MarkdownBase } from './markdown-base.js';

export class MarkdownCliReference extends MarkdownBase {
  public constructor(
    private cliVersion: string,
    private pluginVersions: Array<{ name: string; version: string }>,
    outputDir: string
  ) {
    super(MarkdownBase.file('cli_reference'), outputDir);
  }

  protected generate(): Promise<string> {
    const lines: string[] = [];
    lines.push('> **Note:** This file is autogenerated. Do not edit manually.');
    lines.push('');
    lines.push('# sf CLI Command Reference');
    lines.push('');
    lines.push('An alphabetized list of sf CLI commands and their descriptions, arguments, and flags.');
    lines.push('');
    lines.push(`CLI version: \`${this.cliVersion}\``);
    lines.push('');
    if (this.pluginVersions.length > 0) {
      lines.push('## Plugin Versions');
      lines.push('');
      lines.push('| Plugin | Version |');
      lines.push('|--------|---------|');
      for (const { name, version } of this.pluginVersions) {
        lines.push(`| \`${name}\` | \`${version}\` |`);
      }
      lines.push('');
    }
    return Promise.resolve(lines.join('\n'));
  }
}
