/*
 * Copyright 2026, Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { join } from 'node:path';
import { asString, Dictionary, ensureObject, ensureString } from '@salesforce/ts-types';
import { CommandClass, CommandParameterData, punctuate, replaceConfigVariables } from '../utils.js';
import { buildCommandParameters, FlagInfo, formatParagraphs, readBinary } from '../ditamap/command-helpers.js';
import { MarkdownBase } from './markdown-base.js';

type ParsedExample = {
  description: string;
  commands: string[];
};

export class MarkdownCommand extends MarkdownBase {
  private flags: Dictionary<FlagInfo>;
  private commandMeta: Record<string, unknown>;
  private commandName: string;
  private summary: string | undefined;
  private help: string[];
  private examples: ParsedExample[];
  private state: unknown;
  private deprecated: boolean;

  public constructor(
    topic: string,
    subtopic: string | null,
    command: CommandClass,
    commandMeta: Record<string, unknown> = {},
    outputDir: string
  ) {
    const commandWithUnderscores = ensureString(command.id).replace(/:/g, '_');
    const filename = MarkdownBase.file(`cli_reference_${commandWithUnderscores}`);
    super(filename, outputDir);
    this.destination = join(outputDir, topic, filename);

    this.flags = ensureObject(command.flags);
    this.commandMeta = commandMeta;
    const binary = readBinary(this.commandMeta);

    this.summary = punctuate(command.summary);
    this.commandName = `${binary} ${command.id.replace(/:/g, asString(this.commandMeta.topicSeparator, ' '))}`;

    const description = command.description
      ? replaceConfigVariables(command.description, binary, this.commandName)
      : undefined;

    this.help = formatParagraphs(description);

    this.examples = (command.examples ?? []).map((example) => {
      let desc: string | null;
      let commands: string[];
      if (typeof example === 'string') {
        const parts = example.split('\n');
        desc = parts.length > 1 ? parts[0] : null;
        commands = parts.length > 1 ? parts.slice(1) : [parts[0]];
      } else {
        desc = example.description;
        commands = [example.command];
      }
      return {
        description: replaceConfigVariables(desc ?? '', binary, this.commandName),
        commands: commands.map((cmd) => replaceConfigVariables(cmd, binary, this.commandName)),
      };
    });

    this.state = command.state ?? this.commandMeta.state;
    this.deprecated = (command.deprecated as boolean) ?? this.state === 'deprecated' ?? false;
  }

  protected async generate(): Promise<string> {
    const binary = readBinary(this.commandMeta);
    const parameters = await buildCommandParameters(this.commandName, binary, this.flags);

    const lines: string[] = [];

    lines.push('> **Note:** This file is autogenerated. Do not edit manually.');
    lines.push('');
    lines.push(`# ${this.commandName}`);
    lines.push('');

    if (this.summary) {
      lines.push(this.summary);
      lines.push('');
    }

    if (this.deprecated) {
      lines.push('> **Deprecated**');
      lines.push('');
    } else if (this.state === 'beta') {
      lines.push('> **Beta**');
      lines.push('');
    } else if (this.state === 'preview') {
      lines.push('> **Preview**');
      lines.push('');
    } else if (this.state === 'closedPilot') {
      lines.push('> **Closed Pilot**');
      lines.push('');
    } else if (this.state === 'openPilot') {
      lines.push('> **Open Pilot**');
      lines.push('');
    }

    if (this.help.length > 0) {
      lines.push('## Description');
      lines.push('');
      for (const paragraph of this.help) {
        lines.push(paragraph);
        lines.push('');
      }
    }

    if (parameters.length > 0) {
      lines.push('## Flags');
      lines.push('');
      lines.push('| Flag | Description |');
      lines.push('|------|-------------|');
      for (const param of parameters) {
        lines.push(renderFlagRow(param));
      }
      lines.push('');
    }

    if (this.examples.length > 0) {
      lines.push('## Examples');
      lines.push('');
      for (const example of this.examples) {
        if (example.description) {
          lines.push(example.description);
          lines.push('');
        }
        for (const cmd of example.commands) {
          lines.push('```shell');
          lines.push(cmd.trim());
          lines.push('```');
          lines.push('');
        }
      }
    }

    return lines.join('\n');
  }
}

function renderFlagRow(param: CommandParameterData): string {
  const flagLabel = renderFlagLabel(param);
  const desc = renderFlagDescription(param);
  return `| ${flagLabel} | ${desc} |`;
}

function renderFlagLabel(param: CommandParameterData): string {
  const parts: string[] = [];
  if (param.char) parts.push(`\`-${param.char}\``);
  const longFlag = param.hasValue ? `\`--${param.name} ${param.name.toUpperCase()}\`` : `\`--${param.name}\``;
  parts.push(longFlag);
  return parts.join(', ');
}

function renderFlagDescription(param: CommandParameterData): string {
  const parts: string[] = [];
  if (!param.optional) parts.push('**Required.**');
  const desc = param.description.join(' ').replace(/\|/g, '&#124;');
  if (desc) parts.push(desc);
  if (param.defaultFlagValue) parts.push(`Default: \`${param.defaultFlagValue}\`.`);
  if (param.options?.length) parts.push(`Options: ${param.options.map((o) => `\`${o}\``).join(', ')}.`);
  if (param.deprecated) {
    parts.push(`Deprecated${param.deprecated.to ? `, use \`--${param.deprecated.to}\`` : ''}.`);
  }
  return parts.join(' ').replace(/\n/g, ' ');
}
