/*
 * Copyright 2026, Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MarkdownBase } from './markdown-base.js';

export class MarkdownRootIndex extends MarkdownBase {
  public constructor(private topics: string[], outputDir: string) {
    super(MarkdownBase.file('cli_reference_index'), outputDir);
  }

  protected generate(): Promise<string> {
    const lines: string[] = [];
    lines.push('> **Note:** This file is autogenerated. Do not edit manually.');
    lines.push('');
    lines.push('# sf CLI Reference — Topic Index');
    lines.push('');
    for (const topic of this.topics.sort()) {
      lines.push(`- [${topic}](./${topic}/cli_reference_${topic}.md)`);
    }
    lines.push('');
    return Promise.resolve(lines.join('\n'));
  }
}
