name: publish

on:
  release:
    types: [released]
  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: tag that needs to publish
        type: string
        required: true
jobs:
  npm:
    uses: salesforcecli/github-workflows/.github/workflows/npmPublish.yml@main
    with:
      # ternary-ish https://github.com/actions/runner/issues/409#issuecomment-752775072
      # if the version is 2.x we release it on the `sf` dist tag
      tag: ${{ startsWith( github.event.release.tag_name || inputs.tag, '2.') && 'sf' || 'latest'}}
      githubTag: ${{ github.event.release.tag_name || inputs.tag }}
    secrets: inherit
